// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LearnerModel.proto

package com.toao.quicklearner.persistence;

public final class LearnerModel {
  private LearnerModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.toao.quicklearner.persistence.Model.LearnerType learnerType = 1;
    boolean hasLearnerType();
    com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType getLearnerType();
    
    // optional .com.toao.quicklearner.persistence.Model.Logistic logistic = 2;
    boolean hasLogistic();
    com.toao.quicklearner.persistence.LearnerModel.Model.Logistic getLogistic();
    com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder getLogisticOrBuilder();
  }
  public static final class Model extends
      com.google.protobuf.GeneratedMessage
      implements ModelOrBuilder {
    // Use Model.newBuilder() to construct.
    private Model(Builder builder) {
      super(builder);
    }
    private Model(boolean noInit) {}
    
    private static final Model defaultInstance;
    public static Model getDefaultInstance() {
      return defaultInstance;
    }
    
    public Model getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_fieldAccessorTable;
    }
    
    public enum LearnerType
        implements com.google.protobuf.ProtocolMessageEnum {
      LOGISTIC(0, 0),
      ;
      
      public static final int LOGISTIC_VALUE = 0;
      
      
      public final int getNumber() { return value; }
      
      public static LearnerType valueOf(int value) {
        switch (value) {
          case 0: return LOGISTIC;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<LearnerType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LearnerType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LearnerType>() {
              public LearnerType findValueByNumber(int number) {
                return LearnerType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.toao.quicklearner.persistence.LearnerModel.Model.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final LearnerType[] VALUES = {
        LOGISTIC, 
      };
      
      public static LearnerType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private LearnerType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.toao.quicklearner.persistence.Model.LearnerType)
    }
    
    public interface LogisticOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated .com.toao.quicklearner.persistence.Model.Logistic.InternalLogistic internals = 1;
      java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> 
          getInternalsList();
      com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic getInternals(int index);
      int getInternalsCount();
      java.util.List<? extends com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder> 
          getInternalsOrBuilderList();
      com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder getInternalsOrBuilder(
          int index);
      
      // repeated string labels = 2;
      java.util.List<String> getLabelsList();
      int getLabelsCount();
      String getLabels(int index);
      
      // optional double accuracy = 3;
      boolean hasAccuracy();
      double getAccuracy();
    }
    public static final class Logistic extends
        com.google.protobuf.GeneratedMessage
        implements LogisticOrBuilder {
      // Use Logistic.newBuilder() to construct.
      private Logistic(Builder builder) {
        super(builder);
      }
      private Logistic(boolean noInit) {}
      
      private static final Logistic defaultInstance;
      public static Logistic getDefaultInstance() {
        return defaultInstance;
      }
      
      public Logistic getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_fieldAccessorTable;
      }
      
      public interface InternalLogisticOrBuilder
          extends com.google.protobuf.MessageOrBuilder {
        
        // repeated string feature = 1;
        java.util.List<String> getFeatureList();
        int getFeatureCount();
        String getFeature(int index);
        
        // repeated double omega = 2;
        java.util.List<java.lang.Double> getOmegaList();
        int getOmegaCount();
        double getOmega(int index);
        
        // repeated double mean = 3;
        java.util.List<java.lang.Double> getMeanList();
        int getMeanCount();
        double getMean(int index);
        
        // repeated double stdDev = 4;
        java.util.List<java.lang.Double> getStdDevList();
        int getStdDevCount();
        double getStdDev(int index);
      }
      public static final class InternalLogistic extends
          com.google.protobuf.GeneratedMessage
          implements InternalLogisticOrBuilder {
        // Use InternalLogistic.newBuilder() to construct.
        private InternalLogistic(Builder builder) {
          super(builder);
        }
        private InternalLogistic(boolean noInit) {}
        
        private static final InternalLogistic defaultInstance;
        public static InternalLogistic getDefaultInstance() {
          return defaultInstance;
        }
        
        public InternalLogistic getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_fieldAccessorTable;
        }
        
        // repeated string feature = 1;
        public static final int FEATURE_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList feature_;
        public java.util.List<String>
            getFeatureList() {
          return feature_;
        }
        public int getFeatureCount() {
          return feature_.size();
        }
        public String getFeature(int index) {
          return feature_.get(index);
        }
        
        // repeated double omega = 2;
        public static final int OMEGA_FIELD_NUMBER = 2;
        private java.util.List<java.lang.Double> omega_;
        public java.util.List<java.lang.Double>
            getOmegaList() {
          return omega_;
        }
        public int getOmegaCount() {
          return omega_.size();
        }
        public double getOmega(int index) {
          return omega_.get(index);
        }
        
        // repeated double mean = 3;
        public static final int MEAN_FIELD_NUMBER = 3;
        private java.util.List<java.lang.Double> mean_;
        public java.util.List<java.lang.Double>
            getMeanList() {
          return mean_;
        }
        public int getMeanCount() {
          return mean_.size();
        }
        public double getMean(int index) {
          return mean_.get(index);
        }
        
        // repeated double stdDev = 4;
        public static final int STDDEV_FIELD_NUMBER = 4;
        private java.util.List<java.lang.Double> stdDev_;
        public java.util.List<java.lang.Double>
            getStdDevList() {
          return stdDev_;
        }
        public int getStdDevCount() {
          return stdDev_.size();
        }
        public double getStdDev(int index) {
          return stdDev_.get(index);
        }
        
        private void initFields() {
          feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          omega_ = java.util.Collections.emptyList();;
          mean_ = java.util.Collections.emptyList();;
          stdDev_ = java.util.Collections.emptyList();;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;
          
          memoizedIsInitialized = 1;
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          for (int i = 0; i < feature_.size(); i++) {
            output.writeBytes(1, feature_.getByteString(i));
          }
          for (int i = 0; i < omega_.size(); i++) {
            output.writeDouble(2, omega_.get(i));
          }
          for (int i = 0; i < mean_.size(); i++) {
            output.writeDouble(3, mean_.get(i));
          }
          for (int i = 0; i < stdDev_.size(); i++) {
            output.writeDouble(4, stdDev_.get(i));
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          {
            int dataSize = 0;
            for (int i = 0; i < feature_.size(); i++) {
              dataSize += com.google.protobuf.CodedOutputStream
                .computeBytesSizeNoTag(feature_.getByteString(i));
            }
            size += dataSize;
            size += 1 * getFeatureList().size();
          }
          {
            int dataSize = 0;
            dataSize = 8 * getOmegaList().size();
            size += dataSize;
            size += 1 * getOmegaList().size();
          }
          {
            int dataSize = 0;
            dataSize = 8 * getMeanList().size();
            size += dataSize;
            size += 1 * getMeanList().size();
          }
          {
            int dataSize = 0;
            dataSize = 8 * getStdDevList().size();
            size += dataSize;
            size += 1 * getStdDevList().size();
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }
        
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_descriptor;
          }
          
          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_fieldAccessorTable;
          }
          
          // Construct using com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }
          
          private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }
          
          public Builder clear() {
            super.clear();
            feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            omega_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000002);
            mean_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000004);
            stdDev_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000008);
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.getDescriptor();
          }
          
          public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic getDefaultInstanceForType() {
            return com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.getDefaultInstance();
          }
          
          public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic build() {
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }
          
          private com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return result;
          }
          
          public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic buildPartial() {
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic result = new com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              feature_ = new com.google.protobuf.UnmodifiableLazyStringList(
                  feature_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.feature_ = feature_;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              omega_ = java.util.Collections.unmodifiableList(omega_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.omega_ = omega_;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              mean_ = java.util.Collections.unmodifiableList(mean_);
              bitField0_ = (bitField0_ & ~0x00000004);
            }
            result.mean_ = mean_;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              stdDev_ = java.util.Collections.unmodifiableList(stdDev_);
              bitField0_ = (bitField0_ & ~0x00000008);
            }
            result.stdDev_ = stdDev_;
            onBuilt();
            return result;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic) {
              return mergeFrom((com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic other) {
            if (other == com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.getDefaultInstance()) return this;
            if (!other.feature_.isEmpty()) {
              if (feature_.isEmpty()) {
                feature_ = other.feature_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureFeatureIsMutable();
                feature_.addAll(other.feature_);
              }
              onChanged();
            }
            if (!other.omega_.isEmpty()) {
              if (omega_.isEmpty()) {
                omega_ = other.omega_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureOmegaIsMutable();
                omega_.addAll(other.omega_);
              }
              onChanged();
            }
            if (!other.mean_.isEmpty()) {
              if (mean_.isEmpty()) {
                mean_ = other.mean_;
                bitField0_ = (bitField0_ & ~0x00000004);
              } else {
                ensureMeanIsMutable();
                mean_.addAll(other.mean_);
              }
              onChanged();
            }
            if (!other.stdDev_.isEmpty()) {
              if (stdDev_.isEmpty()) {
                stdDev_ = other.stdDev_;
                bitField0_ = (bitField0_ & ~0x00000008);
              } else {
                ensureStdDevIsMutable();
                stdDev_.addAll(other.stdDev_);
              }
              onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public final boolean isInitialized() {
            return true;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    onChanged();
                    return this;
                  }
                  break;
                }
                case 10: {
                  ensureFeatureIsMutable();
                  feature_.add(input.readBytes());
                  break;
                }
                case 17: {
                  ensureOmegaIsMutable();
                  omega_.add(input.readDouble());
                  break;
                }
                case 18: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  while (input.getBytesUntilLimit() > 0) {
                    addOmega(input.readDouble());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 25: {
                  ensureMeanIsMutable();
                  mean_.add(input.readDouble());
                  break;
                }
                case 26: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  while (input.getBytesUntilLimit() > 0) {
                    addMean(input.readDouble());
                  }
                  input.popLimit(limit);
                  break;
                }
                case 33: {
                  ensureStdDevIsMutable();
                  stdDev_.add(input.readDouble());
                  break;
                }
                case 34: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  while (input.getBytesUntilLimit() > 0) {
                    addStdDev(input.readDouble());
                  }
                  input.popLimit(limit);
                  break;
                }
              }
            }
          }
          
          private int bitField0_;
          
          // repeated string feature = 1;
          private com.google.protobuf.LazyStringList feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          private void ensureFeatureIsMutable() {
            if (!((bitField0_ & 0x00000001) == 0x00000001)) {
              feature_ = new com.google.protobuf.LazyStringArrayList(feature_);
              bitField0_ |= 0x00000001;
             }
          }
          public java.util.List<String>
              getFeatureList() {
            return java.util.Collections.unmodifiableList(feature_);
          }
          public int getFeatureCount() {
            return feature_.size();
          }
          public String getFeature(int index) {
            return feature_.get(index);
          }
          public Builder setFeature(
              int index, String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
            feature_.set(index, value);
            onChanged();
            return this;
          }
          public Builder addFeature(String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureIsMutable();
            feature_.add(value);
            onChanged();
            return this;
          }
          public Builder addAllFeature(
              java.lang.Iterable<String> values) {
            ensureFeatureIsMutable();
            super.addAll(values, feature_);
            onChanged();
            return this;
          }
          public Builder clearFeature() {
            feature_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
          }
          void addFeature(com.google.protobuf.ByteString value) {
            ensureFeatureIsMutable();
            feature_.add(value);
            onChanged();
          }
          
          // repeated double omega = 2;
          private java.util.List<java.lang.Double> omega_ = java.util.Collections.emptyList();;
          private void ensureOmegaIsMutable() {
            if (!((bitField0_ & 0x00000002) == 0x00000002)) {
              omega_ = new java.util.ArrayList<java.lang.Double>(omega_);
              bitField0_ |= 0x00000002;
             }
          }
          public java.util.List<java.lang.Double>
              getOmegaList() {
            return java.util.Collections.unmodifiableList(omega_);
          }
          public int getOmegaCount() {
            return omega_.size();
          }
          public double getOmega(int index) {
            return omega_.get(index);
          }
          public Builder setOmega(
              int index, double value) {
            ensureOmegaIsMutable();
            omega_.set(index, value);
            onChanged();
            return this;
          }
          public Builder addOmega(double value) {
            ensureOmegaIsMutable();
            omega_.add(value);
            onChanged();
            return this;
          }
          public Builder addAllOmega(
              java.lang.Iterable<? extends java.lang.Double> values) {
            ensureOmegaIsMutable();
            super.addAll(values, omega_);
            onChanged();
            return this;
          }
          public Builder clearOmega() {
            omega_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
          }
          
          // repeated double mean = 3;
          private java.util.List<java.lang.Double> mean_ = java.util.Collections.emptyList();;
          private void ensureMeanIsMutable() {
            if (!((bitField0_ & 0x00000004) == 0x00000004)) {
              mean_ = new java.util.ArrayList<java.lang.Double>(mean_);
              bitField0_ |= 0x00000004;
             }
          }
          public java.util.List<java.lang.Double>
              getMeanList() {
            return java.util.Collections.unmodifiableList(mean_);
          }
          public int getMeanCount() {
            return mean_.size();
          }
          public double getMean(int index) {
            return mean_.get(index);
          }
          public Builder setMean(
              int index, double value) {
            ensureMeanIsMutable();
            mean_.set(index, value);
            onChanged();
            return this;
          }
          public Builder addMean(double value) {
            ensureMeanIsMutable();
            mean_.add(value);
            onChanged();
            return this;
          }
          public Builder addAllMean(
              java.lang.Iterable<? extends java.lang.Double> values) {
            ensureMeanIsMutable();
            super.addAll(values, mean_);
            onChanged();
            return this;
          }
          public Builder clearMean() {
            mean_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
          }
          
          // repeated double stdDev = 4;
          private java.util.List<java.lang.Double> stdDev_ = java.util.Collections.emptyList();;
          private void ensureStdDevIsMutable() {
            if (!((bitField0_ & 0x00000008) == 0x00000008)) {
              stdDev_ = new java.util.ArrayList<java.lang.Double>(stdDev_);
              bitField0_ |= 0x00000008;
             }
          }
          public java.util.List<java.lang.Double>
              getStdDevList() {
            return java.util.Collections.unmodifiableList(stdDev_);
          }
          public int getStdDevCount() {
            return stdDev_.size();
          }
          public double getStdDev(int index) {
            return stdDev_.get(index);
          }
          public Builder setStdDev(
              int index, double value) {
            ensureStdDevIsMutable();
            stdDev_.set(index, value);
            onChanged();
            return this;
          }
          public Builder addStdDev(double value) {
            ensureStdDevIsMutable();
            stdDev_.add(value);
            onChanged();
            return this;
          }
          public Builder addAllStdDev(
              java.lang.Iterable<? extends java.lang.Double> values) {
            ensureStdDevIsMutable();
            super.addAll(values, stdDev_);
            onChanged();
            return this;
          }
          public Builder clearStdDev() {
            stdDev_ = java.util.Collections.emptyList();;
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
          }
          
          // @@protoc_insertion_point(builder_scope:com.toao.quicklearner.persistence.Model.Logistic.InternalLogistic)
        }
        
        static {
          defaultInstance = new InternalLogistic(true);
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.toao.quicklearner.persistence.Model.Logistic.InternalLogistic)
      }
      
      private int bitField0_;
      // repeated .com.toao.quicklearner.persistence.Model.Logistic.InternalLogistic internals = 1;
      public static final int INTERNALS_FIELD_NUMBER = 1;
      private java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> internals_;
      public java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> getInternalsList() {
        return internals_;
      }
      public java.util.List<? extends com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder> 
          getInternalsOrBuilderList() {
        return internals_;
      }
      public int getInternalsCount() {
        return internals_.size();
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic getInternals(int index) {
        return internals_.get(index);
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder getInternalsOrBuilder(
          int index) {
        return internals_.get(index);
      }
      
      // repeated string labels = 2;
      public static final int LABELS_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList labels_;
      public java.util.List<String>
          getLabelsList() {
        return labels_;
      }
      public int getLabelsCount() {
        return labels_.size();
      }
      public String getLabels(int index) {
        return labels_.get(index);
      }
      
      // optional double accuracy = 3;
      public static final int ACCURACY_FIELD_NUMBER = 3;
      private double accuracy_;
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getAccuracy() {
        return accuracy_;
      }
      
      private void initFields() {
        internals_ = java.util.Collections.emptyList();
        labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        accuracy_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < internals_.size(); i++) {
          output.writeMessage(1, internals_.get(i));
        }
        for (int i = 0; i < labels_.size(); i++) {
          output.writeBytes(2, labels_.getByteString(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(3, accuracy_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        for (int i = 0; i < internals_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, internals_.get(i));
        }
        {
          int dataSize = 0;
          for (int i = 0; i < labels_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(labels_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getLabelsList().size();
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, accuracy_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.toao.quicklearner.persistence.LearnerModel.Model.Logistic parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_Logistic_fieldAccessorTable;
        }
        
        // Construct using com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getInternalsFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (internalsBuilder_ == null) {
            internals_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            internalsBuilder_.clear();
          }
          labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          accuracy_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDescriptor();
        }
        
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic getDefaultInstanceForType() {
          return com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance();
        }
        
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic build() {
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.toao.quicklearner.persistence.LearnerModel.Model.Logistic buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic buildPartial() {
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic result = new com.toao.quicklearner.persistence.LearnerModel.Model.Logistic(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (internalsBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              internals_ = java.util.Collections.unmodifiableList(internals_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.internals_ = internals_;
          } else {
            result.internals_ = internalsBuilder_.build();
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            labels_ = new com.google.protobuf.UnmodifiableLazyStringList(
                labels_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.labels_ = labels_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000001;
          }
          result.accuracy_ = accuracy_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.toao.quicklearner.persistence.LearnerModel.Model.Logistic) {
            return mergeFrom((com.toao.quicklearner.persistence.LearnerModel.Model.Logistic)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic other) {
          if (other == com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance()) return this;
          if (internalsBuilder_ == null) {
            if (!other.internals_.isEmpty()) {
              if (internals_.isEmpty()) {
                internals_ = other.internals_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureInternalsIsMutable();
                internals_.addAll(other.internals_);
              }
              onChanged();
            }
          } else {
            if (!other.internals_.isEmpty()) {
              if (internalsBuilder_.isEmpty()) {
                internalsBuilder_.dispose();
                internalsBuilder_ = null;
                internals_ = other.internals_;
                bitField0_ = (bitField0_ & ~0x00000001);
                internalsBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getInternalsFieldBuilder() : null;
              } else {
                internalsBuilder_.addAllMessages(other.internals_);
              }
            }
          }
          if (!other.labels_.isEmpty()) {
            if (labels_.isEmpty()) {
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLabelsIsMutable();
              labels_.addAll(other.labels_);
            }
            onChanged();
          }
          if (other.hasAccuracy()) {
            setAccuracy(other.getAccuracy());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder subBuilder = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addInternals(subBuilder.buildPartial());
                break;
              }
              case 18: {
                ensureLabelsIsMutable();
                labels_.add(input.readBytes());
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                accuracy_ = input.readDouble();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated .com.toao.quicklearner.persistence.Model.Logistic.InternalLogistic internals = 1;
        private java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> internals_ =
          java.util.Collections.emptyList();
        private void ensureInternalsIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            internals_ = new java.util.ArrayList<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic>(internals_);
            bitField0_ |= 0x00000001;
           }
        }
        
        private com.google.protobuf.RepeatedFieldBuilder<
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder> internalsBuilder_;
        
        public java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> getInternalsList() {
          if (internalsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(internals_);
          } else {
            return internalsBuilder_.getMessageList();
          }
        }
        public int getInternalsCount() {
          if (internalsBuilder_ == null) {
            return internals_.size();
          } else {
            return internalsBuilder_.getCount();
          }
        }
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic getInternals(int index) {
          if (internalsBuilder_ == null) {
            return internals_.get(index);
          } else {
            return internalsBuilder_.getMessage(index);
          }
        }
        public Builder setInternals(
            int index, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic value) {
          if (internalsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureInternalsIsMutable();
            internals_.set(index, value);
            onChanged();
          } else {
            internalsBuilder_.setMessage(index, value);
          }
          return this;
        }
        public Builder setInternals(
            int index, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder builderForValue) {
          if (internalsBuilder_ == null) {
            ensureInternalsIsMutable();
            internals_.set(index, builderForValue.build());
            onChanged();
          } else {
            internalsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addInternals(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic value) {
          if (internalsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureInternalsIsMutable();
            internals_.add(value);
            onChanged();
          } else {
            internalsBuilder_.addMessage(value);
          }
          return this;
        }
        public Builder addInternals(
            int index, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic value) {
          if (internalsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureInternalsIsMutable();
            internals_.add(index, value);
            onChanged();
          } else {
            internalsBuilder_.addMessage(index, value);
          }
          return this;
        }
        public Builder addInternals(
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder builderForValue) {
          if (internalsBuilder_ == null) {
            ensureInternalsIsMutable();
            internals_.add(builderForValue.build());
            onChanged();
          } else {
            internalsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        public Builder addInternals(
            int index, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder builderForValue) {
          if (internalsBuilder_ == null) {
            ensureInternalsIsMutable();
            internals_.add(index, builderForValue.build());
            onChanged();
          } else {
            internalsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addAllInternals(
            java.lang.Iterable<? extends com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic> values) {
          if (internalsBuilder_ == null) {
            ensureInternalsIsMutable();
            super.addAll(values, internals_);
            onChanged();
          } else {
            internalsBuilder_.addAllMessages(values);
          }
          return this;
        }
        public Builder clearInternals() {
          if (internalsBuilder_ == null) {
            internals_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            internalsBuilder_.clear();
          }
          return this;
        }
        public Builder removeInternals(int index) {
          if (internalsBuilder_ == null) {
            ensureInternalsIsMutable();
            internals_.remove(index);
            onChanged();
          } else {
            internalsBuilder_.remove(index);
          }
          return this;
        }
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder getInternalsBuilder(
            int index) {
          return getInternalsFieldBuilder().getBuilder(index);
        }
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder getInternalsOrBuilder(
            int index) {
          if (internalsBuilder_ == null) {
            return internals_.get(index);  } else {
            return internalsBuilder_.getMessageOrBuilder(index);
          }
        }
        public java.util.List<? extends com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder> 
             getInternalsOrBuilderList() {
          if (internalsBuilder_ != null) {
            return internalsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(internals_);
          }
        }
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder addInternalsBuilder() {
          return getInternalsFieldBuilder().addBuilder(
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.getDefaultInstance());
        }
        public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder addInternalsBuilder(
            int index) {
          return getInternalsFieldBuilder().addBuilder(
              index, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.getDefaultInstance());
        }
        public java.util.List<com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder> 
             getInternalsBuilderList() {
          return getInternalsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder> 
            getInternalsFieldBuilder() {
          if (internalsBuilder_ == null) {
            internalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogisticOrBuilder>(
                    internals_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            internals_ = null;
          }
          return internalsBuilder_;
        }
        
        // repeated string labels = 2;
        private com.google.protobuf.LazyStringList labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureLabelsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            labels_ = new com.google.protobuf.LazyStringArrayList(labels_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<String>
            getLabelsList() {
          return java.util.Collections.unmodifiableList(labels_);
        }
        public int getLabelsCount() {
          return labels_.size();
        }
        public String getLabels(int index) {
          return labels_.get(index);
        }
        public Builder setLabels(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureLabelsIsMutable();
          labels_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addLabels(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllLabels(
            java.lang.Iterable<String> values) {
          ensureLabelsIsMutable();
          super.addAll(values, labels_);
          onChanged();
          return this;
        }
        public Builder clearLabels() {
          labels_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        void addLabels(com.google.protobuf.ByteString value) {
          ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
        }
        
        // optional double accuracy = 3;
        private double accuracy_ ;
        public boolean hasAccuracy() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public double getAccuracy() {
          return accuracy_;
        }
        public Builder setAccuracy(double value) {
          bitField0_ |= 0x00000004;
          accuracy_ = value;
          onChanged();
          return this;
        }
        public Builder clearAccuracy() {
          bitField0_ = (bitField0_ & ~0x00000004);
          accuracy_ = 0D;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.toao.quicklearner.persistence.Model.Logistic)
      }
      
      static {
        defaultInstance = new Logistic(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.toao.quicklearner.persistence.Model.Logistic)
    }
    
    private int bitField0_;
    // required .com.toao.quicklearner.persistence.Model.LearnerType learnerType = 1;
    public static final int LEARNERTYPE_FIELD_NUMBER = 1;
    private com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType learnerType_;
    public boolean hasLearnerType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType getLearnerType() {
      return learnerType_;
    }
    
    // optional .com.toao.quicklearner.persistence.Model.Logistic logistic = 2;
    public static final int LOGISTIC_FIELD_NUMBER = 2;
    private com.toao.quicklearner.persistence.LearnerModel.Model.Logistic logistic_;
    public boolean hasLogistic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic getLogistic() {
      return logistic_;
    }
    public com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder getLogisticOrBuilder() {
      return logistic_;
    }
    
    private void initFields() {
      learnerType_ = com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType.LOGISTIC;
      logistic_ = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLearnerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, learnerType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, logistic_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, learnerType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, logistic_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.toao.quicklearner.persistence.LearnerModel.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.toao.quicklearner.persistence.LearnerModel.Model prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.toao.quicklearner.persistence.LearnerModel.ModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toao.quicklearner.persistence.LearnerModel.internal_static_com_toao_quicklearner_persistence_Model_fieldAccessorTable;
      }
      
      // Construct using com.toao.quicklearner.persistence.LearnerModel.Model.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogisticFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        learnerType_ = com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType.LOGISTIC;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (logisticBuilder_ == null) {
          logistic_ = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance();
        } else {
          logisticBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toao.quicklearner.persistence.LearnerModel.Model.getDescriptor();
      }
      
      public com.toao.quicklearner.persistence.LearnerModel.Model getDefaultInstanceForType() {
        return com.toao.quicklearner.persistence.LearnerModel.Model.getDefaultInstance();
      }
      
      public com.toao.quicklearner.persistence.LearnerModel.Model build() {
        com.toao.quicklearner.persistence.LearnerModel.Model result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.toao.quicklearner.persistence.LearnerModel.Model buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.toao.quicklearner.persistence.LearnerModel.Model result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.toao.quicklearner.persistence.LearnerModel.Model buildPartial() {
        com.toao.quicklearner.persistence.LearnerModel.Model result = new com.toao.quicklearner.persistence.LearnerModel.Model(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.learnerType_ = learnerType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (logisticBuilder_ == null) {
          result.logistic_ = logistic_;
        } else {
          result.logistic_ = logisticBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toao.quicklearner.persistence.LearnerModel.Model) {
          return mergeFrom((com.toao.quicklearner.persistence.LearnerModel.Model)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.toao.quicklearner.persistence.LearnerModel.Model other) {
        if (other == com.toao.quicklearner.persistence.LearnerModel.Model.getDefaultInstance()) return this;
        if (other.hasLearnerType()) {
          setLearnerType(other.getLearnerType());
        }
        if (other.hasLogistic()) {
          mergeLogistic(other.getLogistic());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLearnerType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType value = com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                learnerType_ = value;
              }
              break;
            }
            case 18: {
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder subBuilder = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.newBuilder();
              if (hasLogistic()) {
                subBuilder.mergeFrom(getLogistic());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLogistic(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.toao.quicklearner.persistence.Model.LearnerType learnerType = 1;
      private com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType learnerType_ = com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType.LOGISTIC;
      public boolean hasLearnerType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType getLearnerType() {
        return learnerType_;
      }
      public Builder setLearnerType(com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        learnerType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLearnerType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        learnerType_ = com.toao.quicklearner.persistence.LearnerModel.Model.LearnerType.LOGISTIC;
        onChanged();
        return this;
      }
      
      // optional .com.toao.quicklearner.persistence.Model.Logistic logistic = 2;
      private com.toao.quicklearner.persistence.LearnerModel.Model.Logistic logistic_ = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder> logisticBuilder_;
      public boolean hasLogistic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic getLogistic() {
        if (logisticBuilder_ == null) {
          return logistic_;
        } else {
          return logisticBuilder_.getMessage();
        }
      }
      public Builder setLogistic(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic value) {
        if (logisticBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logistic_ = value;
          onChanged();
        } else {
          logisticBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setLogistic(
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder builderForValue) {
        if (logisticBuilder_ == null) {
          logistic_ = builderForValue.build();
          onChanged();
        } else {
          logisticBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeLogistic(com.toao.quicklearner.persistence.LearnerModel.Model.Logistic value) {
        if (logisticBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              logistic_ != com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance()) {
            logistic_ =
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.newBuilder(logistic_).mergeFrom(value).buildPartial();
          } else {
            logistic_ = value;
          }
          onChanged();
        } else {
          logisticBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearLogistic() {
        if (logisticBuilder_ == null) {
          logistic_ = com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.getDefaultInstance();
          onChanged();
        } else {
          logisticBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder getLogisticBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLogisticFieldBuilder().getBuilder();
      }
      public com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder getLogisticOrBuilder() {
        if (logisticBuilder_ != null) {
          return logisticBuilder_.getMessageOrBuilder();
        } else {
          return logistic_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.toao.quicklearner.persistence.LearnerModel.Model.Logistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder> 
          getLogisticFieldBuilder() {
        if (logisticBuilder_ == null) {
          logisticBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic, com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder, com.toao.quicklearner.persistence.LearnerModel.Model.LogisticOrBuilder>(
                  logistic_,
                  getParentForChildren(),
                  isClean());
          logistic_ = null;
        }
        return logisticBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.toao.quicklearner.persistence.Model)
    }
    
    static {
      defaultInstance = new Model(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.toao.quicklearner.persistence.Model)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toao_quicklearner_persistence_Model_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_toao_quicklearner_persistence_Model_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_toao_quicklearner_persistence_Model_Logistic_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LearnerModel.proto\022!com.toao.quicklear" +
      "ner.persistence\"\214\003\n\005Model\022I\n\013learnerType" +
      "\030\001 \002(\01624.com.toao.quicklearner.persisten" +
      "ce.Model.LearnerType\022C\n\010logistic\030\002 \001(\01321" +
      ".com.toao.quicklearner.persistence.Model" +
      ".Logistic\032\325\001\n\010Logistic\022U\n\tinternals\030\001 \003(" +
      "\0132B.com.toao.quicklearner.persistence.Mo" +
      "del.Logistic.InternalLogistic\022\016\n\006labels\030" +
      "\002 \003(\t\022\020\n\010accuracy\030\003 \001(\001\032P\n\020InternalLogis" +
      "tic\022\017\n\007feature\030\001 \003(\t\022\r\n\005omega\030\002 \003(\001\022\014\n\004m",
      "ean\030\003 \003(\001\022\016\n\006stdDev\030\004 \003(\001\"\033\n\013LearnerType" +
      "\022\014\n\010LOGISTIC\020\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_toao_quicklearner_persistence_Model_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_toao_quicklearner_persistence_Model_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_toao_quicklearner_persistence_Model_descriptor,
              new java.lang.String[] { "LearnerType", "Logistic", },
              com.toao.quicklearner.persistence.LearnerModel.Model.class,
              com.toao.quicklearner.persistence.LearnerModel.Model.Builder.class);
          internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor =
            internal_static_com_toao_quicklearner_persistence_Model_descriptor.getNestedTypes().get(0);
          internal_static_com_toao_quicklearner_persistence_Model_Logistic_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor,
              new java.lang.String[] { "Internals", "Labels", "Accuracy", },
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.class,
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.Builder.class);
          internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_descriptor =
            internal_static_com_toao_quicklearner_persistence_Model_Logistic_descriptor.getNestedTypes().get(0);
          internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_toao_quicklearner_persistence_Model_Logistic_InternalLogistic_descriptor,
              new java.lang.String[] { "Feature", "Omega", "Mean", "StdDev", },
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.class,
              com.toao.quicklearner.persistence.LearnerModel.Model.Logistic.InternalLogistic.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
